name: Npm build to gh-pages

description: installs, builds and publishes dist folder to gh-pages

branding:
  icon: 'upload-cloud'
  color: 'blue'

on:
  workflow_call:
    secrets: inherit

inputs:
  github_token:
    description: 'Set a generated GITHUB_TOKEN for pushing to the remote branch.'
    required: false


runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install
      shell: bash
    - run: npm run build
      shell: bash

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./dist
